-- -------------------------------------------------------------
-- 
-- File Name: C:\EELE_466\lab3\hdl_coder_Madgwick_qDot\codegen\Madgwick_qDot\hdlsrc\Madgwick_qDot_fixpt_tc.vhd
-- Created: 2018-01-30 13:06:53
-- 
-- Generated by MATLAB 9.1, MATLAB Coder 3.2 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Madgwick_qDot_fixpt_tc
-- Source Path: Madgwick_qDot_fixpt_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clkenable
-- 
-- enb         : identical to clkenable
-- enb_1_4_0   : 4x slower than clkenable with last phase
-- enb_1_4_1   : 4x slower than clkenable with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Madgwick_qDot_fixpt_tc IS
  PORT( clk                               :   IN    std_logic;
        resetx                            :   IN    std_logic;
        clkenable                         :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_4_0                         :   OUT   std_logic;
        enb_1_4_1                         :   OUT   std_logic
        );
END Madgwick_qDot_fixpt_tc;


ARCHITECTURE rtl OF Madgwick_qDot_fixpt_tc IS

  -- Signals
  SIGNAL count4                           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;

BEGIN
  Counter4 : PROCESS (clk, resetx)
  BEGIN
    IF resetx = '1' THEN
      count4 <= to_unsigned(1, 2);
    ELSIF rising_edge(clk) THEN
      IF clkenable = '1' THEN
        IF count4 = to_unsigned(3, 2) THEN
          count4 <= to_unsigned(0, 2);
        ELSE
          count4 <= count4 + 1;
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter4;

  phase_all <= '1' WHEN clkenable = '1' ELSE '0';

  temp_process1 : PROCESS (clk, resetx)
  BEGIN
    IF resetx = '1' THEN
      phase_0 <= '0';
    ELSIF rising_edge(clk) THEN
      IF clkenable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count4 = to_unsigned(3, 2) AND clkenable = '1' ELSE '0';

  temp_process2 : PROCESS (clk, resetx)
  BEGIN
    IF resetx = '1' THEN
      phase_1 <= '1';
    ELSIF rising_edge(clk) THEN
      IF clkenable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  phase_1_tmp <= '1' WHEN count4 = to_unsigned(0, 2) AND clkenable = '1' ELSE '0';

  enb <=  phase_all AND clkenable;

  enb_1_4_0 <=  phase_0 AND clkenable;

  enb_1_4_1 <=  phase_1 AND clkenable;


END rtl;

