%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.3 and Fixed-Point Designer 6.0           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [ax,ay,az,a0] = Madgwick_normalize_wrapper_fixpt(ax,ay,az,a0)
    fm = get_fimath();
    ax_in = fi( ax, 1, 14, 5, fm );
    ay_in = fi( ay, 1, 14, 5, fm );
    az_in = fi( az, 1, 14, 5, fm );
    a0_in = fi( a0, 1, 14, 5, fm );
    [ax_out,ay_out,az_out,a0_out] = Madgwick_normalize_fixpt( ax_in, ay_in, az_in, a0_in );
    ax = double( ax_out );
    ay = double( ay_out );
    az = double( az_out );
    a0 = double( a0_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
