%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.1 and Fixed-Point Designer 5.3           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [qDot1,qDot2,qDot3,qDot4] = Madgwick_qDot_wrapper_fixpt(q0,q1,q2,q3,gx,gy,gz)
    fm = get_fimath();
    q0_in = fi( q0, 0, 14, 14, fm );
    q1_in = fi( q1, 0, 14, 14, fm );
    q2_in = fi( q2, 0, 14, 14, fm );
    q3_in = fi( q3, 0, 14, 14, fm );
    gx_in = fi( gx, 1, 14, 7, fm );
    gy_in = fi( gy, 1, 14, 7, fm );
    gz_in = fi( gz, 1, 14, 7, fm );
    [qDot1_out,qDot2_out,qDot3_out,qDot4_out] = Madgwick_qDot_fixpt( q0_in, q1_in, q2_in, q3_in, gx_in, gy_in, gz_in );
    qDot1 = double( qDot1_out );
    qDot2 = double( qDot2_out );
    qDot3 = double( qDot3_out );
    qDot4 = double( qDot4_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
